dataset: argoverse_v2
input_dim: 2
hidden_dim: 128
output_dim: 2
output_head: false
num_historical_steps: 50
num_future_steps: 60
num_modes: 6
num_recurrent_steps: 3
num_freq_bands: 64
num_map_layers: 1
num_agent_layers: 2
num_dec_layers: 2
num_heads: 8
head_dim: 16
dropout: 0.1
pl2pl_radius: 150.0
time_span: 10
pl2a_radius: 50.0
a2a_radius: 50.0
num_t2m_steps: 30
pl2m_radius: 150.0
a2m_radius: 150.0
lr: 0.0005
weight_decay: 0.0001
T_max: 64
submission_dir: ./
submission_file_name: submission
root: /leonardo_scratch/large/userexternal/lbonin00/argoverse/argoverse_data/
train_batch_size: 4
val_batch_size: 4
test_batch_size: 4
shuffle: true
num_workers: 8
pin_memory: true
persistent_workers: true
train_raw_dir: null
val_raw_dir: null
test_raw_dir: null
train_processed_dir: null
val_processed_dir: null
test_processed_dir: null
accelerator: auto
devices: 1
max_epochs: 64
