train_batch_size : 16
val_batch_size : 4
test_batch_size : 4
shuffle : True
num_workers : 4
pin_memory : True
persistent_workers : True
dataset: argoverse_v2
num_historical_steps: 50
num_future_steps: 60
num_recurrent_steps: 3
pl2pl_radius: 150
time_span: 10
pl2a_radius: 50
a2a_radius: 50
num_t2m_steps: 30
pl2m_radius: 150
a2m_radius: 150
devices: 1
accelerator: auto
qcnet_ckpt_path: Da aggiungere
num_denoiser_layers: 3 
num_diffusion_steps: 100
T_max: 30 
max_epochs: 30 
lr: 0.005 
beta_1: 0.0001 
beta_T: 0.05 
diff_type : opd 
sampling: ddim 
sampling_stride: 10 
num_eval_samples: 6 
choose_best_mode: FDE 
std_reg: 0.3 
check_val_every_n_epoch: 3 
path_pca_s_mean: 'pca/imp_org/s_mean_10.npy' 
path_pca_VT_k : 'pca/imp_org/VT_k_10.npy' 
path_pca_V_k : 'pca/imp_org/V_k_10.npy' 
path_pca_latent_mean : 'pca/imp_org/latent_mean_10.npy' 
path_pca_latent_std : 'pca/imp_org/latent_std_10.npy'

ex_opm: 0
std_state: est
cluster: traj
cluster_max_thre: 2.5
cluster_mean_thre: 2.5
    
guid_sampling: no_guid
guid_task: none
guid_method: none
guid_plot: no_plot

cond_norm: 0
cost_param_costl : 1.0
cost_param_threl: 1.0